### ISSUE TITLE
README needs application summary

### ISSUE THREAD

**Issue by CHBaker** [Fullaxx/ReStatGui#2]
ADD summary of application functionality:

- basic functionality
- use cases
- scalability
- current use

anything else

**Comment by Fullaxx** [comment]
ReStat is a simple data collection tool for server status.
It has a few independent pieces that collect important information
and includes a web interface to display the information in real time.
The goal is to collect and monitor system status and be as lightweight as possible.
It can be run on as many machines as you would like.
