### ISSUE TITLE
README needs CONFIGURATION

### ISSUE THREAD

**Issue by CHBaker** [Fullaxx/ReStatGui#4]
Add configuration section to README.md

This could include:

- Project location within file structure
- running any dependencies for local host or live app (virtual machines, or whatever is the most 
       basic way to get app running)
- commands to run project
- where it will be hosted based on configuration

*be as detailed as possible, to make setup for users clear and easy

**Comment by Fullaxx** [comment]
Closed with commit 570fdc48cdabec74a09ba3c5604841c1ceed3d37
