### ISSUE TITLE
Create code of conduct doc

### ISSUE THREAD

**Issue by CHBaker** [Fullaxx/ReStatGui#9]
We need a doc laying out the code of conduct for ALL contributors for this project, We should add this as well as #7 Inside a docs folder.

a good example for a code of conduct is [here](https://github.com/mozilla/testpilot/blob/master/docs/code_of_conduct.md)

we could just use that one as long as we are not infringing on copyright

**Comment by Fullaxx** [comment]
Closed with commit b6a21e2
